name: polytechcolloscopeclient
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  collection: ^1.17.2
  dotenv: ^4.2.0
  equatable: ^2.0.5
  hive: ^2.2.3
  copy_with_extension: ^5.0.4
  html: ^0.15.4
  requests_plus: ^4.8.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  build_runner: ^2.2.0
  hive_generator: ^2.0.0
  copy_with_extension_gen: ^5.0.2
